"""Modified Blogs table relational column name.

Revision ID: 12da7c7e2aea
Revises: 283b5d3e0958
Create Date: 2019-04-28 13:17:27.417460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12da7c7e2aea'
down_revision = '283b5d3e0958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_constraint('blogs_user_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['author'], ['id'])
    op.drop_column('blogs', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_user_fkey', 'blogs', 'users', ['user'], ['id'])
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
