"""Blogs table change update.

Revision ID: 13dd3f83f33a
Revises: 12da7c7e2aea
Create Date: 2019-04-28 13:32:14.233205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dd3f83f33a'
down_revision = '12da7c7e2aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('writer', sa.String(length=255), nullable=True))
    op.drop_constraint('blogs_author_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['blogger'], ['id'])
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_author_fkey', 'blogs', 'users', ['author'], ['id'])
    op.drop_column('blogs', 'writer')
    # ### end Alembic commands ###
