"""Added column blogger to the blogs table.

Revision ID: 283b5d3e0958
Revises: decc939a8aed
Create Date: 2019-04-28 13:12:01.147125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283b5d3e0958'
down_revision = 'decc939a8aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('user', sa.Integer(), nullable=True))
    op.drop_constraint('blogs_blogger_fkey', 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key('blogs_blogger_fkey', 'blogs', 'users', ['blogger'], ['id'])
    op.drop_column('blogs', 'user')
    # ### end Alembic commands ###
