"""Added comments' table to the database.

Revision ID: d0518e71cb9b
Revises: 13dd3f83f33a
Create Date: 2019-04-28 15:09:30.023110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0518e71cb9b'
down_revision = '13dd3f83f33a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('blogger', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blogger'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic'], ['blogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
